version: '3'
services:
  exchange-rates-api:
    build:
      context: .
    ports:
    - 8888:8080
    environment:
    - PORT=8080
    - APP_ID=${APP_ID}
    - FX_API=https://openexchangerates.org/api/
    - NODE_ENV=production
    container_name: exchange-rates-api